name: json_api
version: 4.3.0
description: "Framework-agnostic implementations of JSON:API Client (Flutter, Web and VM) and Server (VM). Supports JSON:API v1.0 (http://jsonapi.org)"
homepage: "https://github.com/f3ath/json-api-dart"

dependencies:
  http:
  http_parser:

dev_dependencies:
  args:
  json_matcher:
  pedantic:
  shelf:
  stream_channel:
  test:
  test_coverage:
  uuid:

environment:
  sdk: ">=2.7.0 <3.0.0"
